### ISSUE TITLE
feature request: expose functions to iOS Shortcuts

### ISSUE THREAD

**Issue by slowburn** [xaphod/CrankIt#1]
Hi, would it be possible to expose the main functions to iOS Shortcuts, that would make for some great automation options.

**Comment by xaphod** [comment]
@slowburn Sorry i'm only seeing this after some years. Can you list the ones you think should be added? I don't want to add 20 but i'll add some for sure. I'm not at all familiar with iOS shortcuts so please point me to the apple docs that show me the right way to expose this for you (intents?)

**Comment by slowburn** [comment]
@xaphod thx for coming back to this.
unfortunately it's not of use to me anymore. I first created some shortcuts that use netcat (nc) commands to adjust various settings (input/station/volume) but meanwhile moved on to have a set of the heos CLI commands run directly on a RaspPi and have a web frontend that allows access from all local devices.
